[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[functions]
  directory = "../backend/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200